# Generated by Django 4.2.17 on 2024-12-22 05:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('masala', '0002_kaleshi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaleshi',
            name='kaleshi_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kaleshi',
            name='kaleshi_slug',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
