# Generated by Django 4.2.17 on 2024-12-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masala', '0003_kaleshi_kaleshi_response_kaleshi_kaleshi_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalesh',
            name='response_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
